version: '3.9'

services:
  mydb:
      image: mysql:latest
      container_name: mydb
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_DATABASE=AREPdb
      volumes:
        - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: arep-taller7
    container_name: app
    ports:
      - "57000:57000"
    depends_on:
      - mydb
    volumes:
      - ./app:/app
volumes:
  mysql_data:
